### ISSUE TITLE
Intake Code To-Do List

### ISSUE THREAD

**Issue by Akhil353** [Akhil353/Group-1-Repo#1]
- [ ] Compress air to store for pistons
- [ ] Extend/Retract pistons
- [ ] Spin wheels forward/backward
